[2023-04-26T09:11:08.068+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: slack_processing.print_the_context scheduled__2023-04-25T00:00:00+00:00 [queued]>
[2023-04-26T09:11:08.074+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: slack_processing.print_the_context scheduled__2023-04-25T00:00:00+00:00 [queued]>
[2023-04-26T09:11:08.074+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T09:11:08.075+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-04-26T09:11:08.075+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T09:11:08.083+0000] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): print_the_context> on 2023-04-25 00:00:00+00:00
[2023-04-26T09:11:08.087+0000] {standard_task_runner.py:55} INFO - Started process 14607 to run task
[2023-04-26T09:11:08.091+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'slack_processing', 'print_the_context', 'scheduled__2023-04-25T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/slack_processing.py', '--cfg-path', '/tmp/tmp900w7lbn']
[2023-04-26T09:11:08.091+0000] {standard_task_runner.py:83} INFO - Job 33: Subtask print_the_context
[2023-04-26T09:11:08.143+0000] {task_command.py:388} INFO - Running <TaskInstance: slack_processing.print_the_context scheduled__2023-04-25T00:00:00+00:00 [running]> on host 182d53144720
[2023-04-26T09:11:08.188+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=slack_processing
AIRFLOW_CTX_TASK_ID=print_the_context
AIRFLOW_CTX_EXECUTION_DATE=2023-04-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-25T00:00:00+00:00
[2023-04-26T09:11:08.190+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/slack_processing.py", line 20, in pass_or_fail
    raise ValueError(f"Random number {num} is less than 0.5!")
ValueError: Random number 3 is less than 0.5!
[2023-04-26T09:11:08.200+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=slack_processing, task_id=print_the_context, execution_date=20230425T000000, start_date=20230426T091108, end_date=20230426T091108
[2023-04-26T09:11:08.206+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 33 for task print_the_context (Random number 3 is less than 0.5!; 14607)
[2023-04-26T09:11:08.223+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-26T09:11:08.242+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
