[2023-04-26T09:11:31.156+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: slack_processing.print_the_context manual__2023-04-26T09:11:30.448882+00:00 [queued]>
[2023-04-26T09:11:31.161+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: slack_processing.print_the_context manual__2023-04-26T09:11:30.448882+00:00 [queued]>
[2023-04-26T09:11:31.161+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T09:11:31.162+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-04-26T09:11:31.162+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T09:11:31.169+0000] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): print_the_context> on 2023-04-26 09:11:30.448882+00:00
[2023-04-26T09:11:31.174+0000] {standard_task_runner.py:55} INFO - Started process 14636 to run task
[2023-04-26T09:11:31.177+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'slack_processing', 'print_the_context', 'manual__2023-04-26T09:11:30.448882+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/slack_processing.py', '--cfg-path', '/tmp/tmp950169fr']
[2023-04-26T09:11:31.177+0000] {standard_task_runner.py:83} INFO - Job 35: Subtask print_the_context
[2023-04-26T09:11:31.225+0000] {task_command.py:388} INFO - Running <TaskInstance: slack_processing.print_the_context manual__2023-04-26T09:11:30.448882+00:00 [running]> on host 182d53144720
[2023-04-26T09:11:31.269+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=slack_processing
AIRFLOW_CTX_TASK_ID=print_the_context
AIRFLOW_CTX_EXECUTION_DATE=2023-04-26T09:11:30.448882+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-26T09:11:30.448882+00:00
[2023-04-26T09:11:31.270+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/slack_processing.py", line 20, in pass_or_fail
    raise ValueError(f"Random number {num} is less than 0.5!")
ValueError: Random number 4 is less than 0.5!
[2023-04-26T09:11:31.278+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=slack_processing, task_id=print_the_context, execution_date=20230426T091130, start_date=20230426T091131, end_date=20230426T091131
[2023-04-26T09:11:31.285+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 35 for task print_the_context (Random number 4 is less than 0.5!; 14636)
[2023-04-26T09:11:31.308+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-26T09:11:31.328+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
